### ISSUE TITLE
Your work on the AROSYS project for RobMoSys

### ISSUE THREAD

**Issue by leasuika** [cyberbotics/AROSYS#68]
To whom it may concern,

I am a computer science student at the Technische Universität Dresden (Germany) and I am currently working on a research project regarding Model Driven Engineering in robotics and the RobMoSys project. 
As a part of my research I want to include an overview of pilot studies and pilot projects regarding RobMoSys. I have come across your project AROSYS and would love to know more about it. Specifically, I would like to know within what time frame you worked on the project and whether it was finished or is still in development. 
Furthermore, I would love to know whether you could give me an outlook regarding future aspects of your project. Has the project inspired any other projects related to RobMoSys and model driven engineering?

Thank you for your time in advance and I hope to hear from you.

Kind regards

**Comment by omichel** [comment]
This project was finished three years ago. You will find more information about it [here](https://robmosys.eu/arosys/). It was re-used in the [SeRoNet project](https://www.seronet-projekt.de) and in the [Xito](https://www.xito.one) marketplace.
